### ISSUE TITLE
Normalization & Imputation error

### ISSUE THREAD

**Issue by msuriyan** [xryanglab/SCASL#11]
Hi there,

I am running the SCASL demo to check if my installations are fine. However, I am facing an error with the normalization and imputation step.  

(scasl) lab@server2:/media/SCASL_splicing/SCASL-main$ python main.py -y configs/srr_star_demo.yaml
=============Preprocessing=============
Loading site names: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:01<00:00, 35.25it/s]
Reading and processing junction files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:01<00:00, 30.40it/s]
=============Filtering=============
reading file...
done.
executing repeat and initial threshold filter...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17851/17851 [00:14<00:00, 1261.41it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17818/17818 [00:13<00:00, 1273.85it/s]
done
executing sites quality filter by threshold
the site histogram is saved at process_result/20241108114532/img/site_hist.png
the descriptions of the non-NaN data of sites are shown below
count    40297.000000
mean         7.669926
std          6.271053
min          3.000000
0%           3.000000
10%          4.000000
20%          4.000000
30%          4.000000
40%          4.000000
50%          5.000000
60%          6.000000
70%          8.000000
80%         11.000000
90%         17.000000
max         40.000000
dtype: float64
the site histogram is saved at process_result/20241108114532/img/site_hist.png
the descriptions of the non-NaN data of sites are shown below
count    40138.000000
mean         7.703000
std          6.293347
min          3.000000
0%           3.000000
10%          4.000000
20%          4.000000
30%          4.000000
40%          4.000000
50%          5.000000
60%          6.000000
70%          8.000000
80%         11.000000
90%         17.000000
max         40.000000
dtype: float64
done.
remove the duplicated site starts and ends...
done.
executing sample quality filter...
the sample histogram is saved at process_result/20241108114532/img/sample_hist.png
the descriptions of the non-NaN data of sites are shown below
count       40.000000
mean     14823.125000
std      17859.287926
min       1407.000000
0%        1407.000000
10%       3657.600000
20%       4658.000000
30%       5990.200000
40%       8024.400000
50%       9009.000000
60%      12487.600000
70%      13943.100000
80%      17898.800000
90%      22226.700000
max      73079.000000
dtype: float64
done.
saving...
done.
=============Normalization & Imputation=============
reading data from process_result/20241108114532/filtered_matrix...
Traceback (most recent call last):
  File "/media/SCASL_splicing/SCASL-main/main.py", line 10, in <module>
    scasl.fit()
  File "/media/SCASL_splicing/SCASL-main/scasl/splice.py", line 95, in fit
    run_cluster(self.cfg)
  File "/media/SCASL_splicing/SCASL-main/scasl/splice.py", line 66, in run_cluster
    df_final, mat = normalize(filter_path, cfg.impute.num_iteration, cfg.impute.knn)
  File "/media/SCASL_splicing/SCASL-main/scasl/normalize.py", line 92, in normalize
    dfs = norm_only(df_path, 'start')
  File "/media/SCASL_splicing/SCASL-main/scasl/normalize.py", line 40, in norm_only
    df_prob = to_prob(df, groupby=groupby)
  File "/media/SCASL_splicing/SCASL-main/scasl/normalize.py", line 22, in to_prob
    sums = sums.drop(columns=['start', 'end'])
  File "/home/lab/miniconda3/envs/scasl/lib/python3.9/site-packages/pandas/core/frame.py", line 5581, in drop
    return super().drop(
  File "/home/lab/miniconda3/envs/scasl/lib/python3.9/site-packages/pandas/core/generic.py", line 4788, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/lab/miniconda3/envs/scasl/lib/python3.9/site-packages/pandas/core/generic.py", line 4830, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/lab/miniconda3/envs/scasl/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 7070, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['end'] not found in axis"

Any help would be useful.

Thanks.

**Comment by whuyanzeng** [comment]
![Image](https://github.com/user-attachments/assets/51e2444d-6dd4-4f47-8f80-8d4eefd59904)
I solved this problem by modifying this chunk of codes in SCASL/scasl/normalize.py

**Comment by xiaobearxiaobear** [comment]
@oldcountlost @YangLabProject 
hi,
Could you help me clarify something? I'm not quite sure about the biological significance of each SRR in this demo. I would like to know if I can use SCASL for clustering if my experimental group has 6 SRRs and my control group has 6 SRRs. Also, how should I prepare my label.csv file?

**Comment by brandon-hastings** [comment]
I was able to solve this by installing from the requirements.txt file included in the repository, so it is likely caused by a dependency issue that is introduced if following the environment setup instructions currently outlined in the readme. Instead of following the install instructions on the readme, setup the conda environment using: `conda create --name scasl --file path/to/requirements.txt`

The readme could use some clarification on the environment setup in light of this.

**Comment by Melody020311** [comment]
Replace the `to_prob `function in normalize.py with the following:

```
def to_prob(df, groupby):
    import pandas as pd
    import numpy as np

    sums = df.groupby(groupby).sum(min_count=1, numeric_only=True).reset_index()

    merged = pd.merge(df, sums, how='left', on=groupby, suffixes=('_x', '_y'))

    other_coord = list(set(['start', 'end']).difference([groupby]))
    other = other_coord[0]

    drop_cols = [f"{other}_x", f"{other}_y", groupby]
    merged = merged.drop(columns=drop_cols, errors='ignore')

    meta = set(['start', 'end'])
    sample_cols = [c for c in df.columns if c not in meta]
    sample_cols = [c for c in sample_cols if pd.api.types.is_numeric_dtype(df[c])]

    denom_cols = [f"{c}_y" for c in sample_cols]
    num = df[sample_cols].to_numpy(dtype=float)

    missing = [c for c in denom_cols if c not in merged.columns]
    if missing:
        raise ValueError(f"Missing denominator columns after merge: {missing[:10]} ...")

    den = merged[denom_cols].to_numpy(dtype=float)
    den[den == 0] = np.nan

    probs = num / den
    probs = np.nan_to_num(probs, nan=0.0, posinf=0.0, neginf=0.0)

    df_result = df.copy()
    df_result.loc[:, sample_cols] = probs
    df_result = df_result.sort_values(by=groupby)
    return df_result

```
